<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Template Name: Sitemap

//* Remove standard post content output
remove_action( 'genesis_post_content', 'genesis_do_post_content' );
remove_action( 'genesis_entry_content', 'genesis_do_post_content' );

add_action( 'genesis_entry_content', 'genesis_page_archive_content' );
add_action( 'genesis_post_content', 'genesis_page_archive_content' );


/**
 * This function outputs sitemap-esque columns displaying all pages,
 * categories, authors, monthly archives, and recent posts.
 *
 * @since 1.6
 *
 * @uses genesis_a11y() to check for headings choice.
 * @uses genesis_sitemap() to generate the sitemap.
 *
 */

/*function genesis_page_archive_content() {

	$heading = ( genesis_a11y( 'headings' ) ? 'h2' : 'h4' );

	genesis_sitemap( $heading );

}
*/

function genesis_page_archive_content() { ?>

<?php echo genesis_html5() ? '<article>' : '<div>'; ?>
<h4><?php _e("Site Feeds", "genesis"); ?></h4>
<ul>
<li><a href="<?php bloginfo('rss2_url'); ?>"><?php _e("Main RSS Feed", "genesis"); ?></a></li>
<li><a href="<?php bloginfo('comments_rss2_url'); ?>"><?php _e("Comments RSS Feed", "genesis"); ?></a></li>
</ul>


	<h4><?php _e( 'Pages:', 'genesis' ); ?>test</h4>
	<ul>
		<?php wp_list_pages( 'title_li=' ); ?>
	</ul>

	<h4><?php _e( 'Products', 'woocommerce' ); ?></h4>
	<ul>
		<?php wp_list_products( 'title_li=' ); ?>
	</ul>

	<h4><?php _e( 'Categories:', 'genesis' ); ?></h4>
	<ul>
		<?php wp_list_categories( 'sort_column=name&title_li=' ); ?>
	</ul>

	<h4><?php _e( 'Authors:', 'genesis' ); ?></h4>
	<ul>
		<?php wp_list_authors( 'exclude_admin=0&optioncount=1' ); ?>
	</ul>

	<h4><?php _e( 'Monthly:', 'genesis' ); ?></h4>
	<ul>
		<?php wp_get_archives( 'type=monthly' ); ?>
	</ul>

	<h4><?php _e( 'Recent Posts:', 'genesis' ); ?></h4>
	<ul>
		<?php wp_get_archives( 'type=postbypost&limit=100' ); ?>
	</ul>

<div class="sitemap">
<h4><?php _e("Popular Tags", "genesis"); ?></h4>
<?php wp_tag_cloud('number=0&smallest=8&largest=22&format=list&orderby=count&order=DESC'); ?> 
</div>

<?php
echo genesis_html5() ? '</article>' : '</div>';
}


genesis();
